CREATE TABLE form(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	age VARCHAR (100),
	sinntyou  VARCHAR(100) NOT NULL,
	taijuu VARCHAR(100) NOT NULL,
	ketuatuue VARCHAR(100) NOT NULL,
	ketuatusita VARCHAR(100) NOT NULL,
	memo VARCHAR (100),
	type VARCHAR (100),
	PRIMARY KEY(id)
);
CREATE TABLE batform(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(100),
	age VARCHAR (100),
	sinntyou  VARCHAR(100),
	taijuu VARCHAR(100),
	ketuatuue VARCHAR(100),
	ketuatusita VARCHAR(100),
	memo VARCHAR (100) ,
	type VARCHAR (100) ,
	PRIMARY KEY(id)
);